### PR TITLE
Update PdfinfoService.php

### PR DESCRIPTION
**Pull request by responseinformationsdesign**
Solves error with metadata containing special characters (f. e. German umlauts)

### CODE REVIEW

**Comment by Avalarion** [comment]
Hey @responseinformationsdesign this is just a mirror of https://review.typo3.org/#/admin/projects/TYPO3CMS/Extensions/Extractor ( which is a gerrit system ) and is read only.

But perhaps @xperseguers will merge this manually in gerrit.

Have a nice evening,

Bastian

**Comment by responseinformationsdesign** [comment]
Still wrong in version 1.4.0. Could you please correct this obvious bug?

**Comment by xperseguers** [comment]
Looks like you reported the bug correctly here: https://forge.typo3.org/issues/78070 because github is not the platform in use for this extension. Sorry for not taking care earlier. Was not impacted by this problem and I did not see you provided a patch in the form of a comment. Will do the real patch as you did here.

**Comment by xperseguers** [comment]
@Avalarion Could you please reject and close this PR?

**Comment by Avalarion** [comment]
Closing this pull request.

**Pull request closed without merging**
